[project]
name = "tallbrachiosaurus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tallbrachiosaurus", email = "322250098+tallbrachiosaurus@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[tool.maturin]
module-name = "tallbrachiosaurus._core"
python-packages = ["tallbrachiosaurus"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
